export const SIXTY = 60 as const;
export const ONE_HUNDRED = 100 as const;
export const ONE_THOUSAND = 1000 as const;

export enum USER_TYPE {
  MASTER_ADMIN = 'MASTER_ADMIN',
  ADMIN = 'ADMIN',
  USER = 'USER',
  VENDOR = 'VENDOR',
}

export enum GENDER {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  DO_NOT_TELL = 'DO_NOT_TELL',
  NONE = 'NONE',
}

export enum SIGN_UP_TYPE {
  APP = 'APP',
  GOOGLE = 'GOOGLE',
  APPLE = 'APPLE',
  META = 'META',
}

export enum OTP_TYPE {
  EMAIL = 'EMAIL',
  MOBILE = 'MOBILE',
  ACCOUNT_CREATE = 'ACCOUNT_CREATE',
  FORGET_PASSWORD = 'FORGET_PASSWORD',
}

export enum AUTH_ACTION_TYPE {
  SIGN_IN = 'SIGN_IN',
  SIGN_OUT = 'SIGN_OUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
}

export enum TOKEN_TYPE {
  ACCESS_TOKEN = 'ACCESS_TOKEN',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  OTP_TOKEN = 'OTP_TOKEN',
  FORGET_PASSWORD_TOKEN = 'FORGET_PASSWORD_TOKEN',
  ORDER_TOKEN = 'ORDER_TOKEN',
}

export enum USER_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum COMMON_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
}

export enum PRODUCT_SPECIFICATION_QUANTITY_TYPE {
  CM = 'cm',
  METER = 'meter',
  INCH = 'inch',
  FOOT = 'foot',
  ML = 'ml',
  UNIT = 'unit',
  KG = 'kg',
  GRAM = 'gram',
  NONE = 'none',
}

export enum PRODUCT_SPECIFICATION_VALUE_TYPE {
  SINGLE = 'SINGLE',
  MULTIPLE = 'MULTIPLE',
}

export enum PRODUCT_COMMON_STATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  OUT_OF_STOCK = 'OUT_OF_STOCK',
}

export const PRODUCT_SKU_START = 10000;

export const ORDER_NUMBER_START = 10000;

export enum PRODUCT_LOT_TYPE {
  SELL = 'SELL',
  PURCHASE = 'PURCHASE',
  TRANSFER = 'TRANSFER',
}

export enum ORDER_STATUS {
  PENDING = 'PENDING',
  PLACED = 'PLACED',
  CONFIRMED = 'CONFIRMED',
  CANCELLED = 'CANCELLED',
}

export enum ORDER_TYPE {
  SELL = 'SELL',
  PURCHASE = 'PURCHASE',
  SELL_RETURN = 'SELL_RETURN',
  PURCHASE_RETURN = 'PURCHASE_RETURN',
}
